import os
from typing import Dict, List, Any
from dataclasses import dataclass

@dataclass
class DraftReport:
    markdown: str

class Writer:
    """Writer Agent – converts findings to executive reports"""

    def __init__(self):
        print("📝 Writer Agent initialized")

    def draft(self, facts: Dict[str, Any], figures: List[str]) -> DraftReport:
        try:
            markdown_parts = []
            markdown_parts.append("# 🧠 Executive Sales Optimization Report\n")
            markdown_parts.append("*Generated by MaRGen Multi-Agent System*\n---\n")

            # ------------------------------------------------------------
            # Summary
            markdown_parts.append("## 📋 Executive Summary\n")
            markdown_parts.append("This report analyzes restaurant sales to identify promotion, weather, and cuisine impacts on revenue.\n")

            if "total_revenue" in facts:
                markdown_parts.append(f"- Total Revenue: ${facts['total_revenue']:,.2f}")
            if "avg_revenue" in facts:
                markdown_parts.append(f"- Average Revenue per Item: ${facts['avg_revenue']:,.2f}")
            if "top_category" in facts:
                markdown_parts.append(f"- Top Category: **{facts['top_category']}**")

            # ------------------------------------------------------------
            # Promotion Effect
            if "promotion_effect" in facts:
                markdown_parts.append("\n## 🎯 Promotion Effect Analysis")
                promo = facts["promotion_effect"]
                markdown_parts.append(f"- No Promo Avg Revenue: ${promo.get('No Promo',0):,.2f}")
                markdown_parts.append(f"- Promo Avg Revenue: ${promo.get('Promo',0):,.2f}")
                markdown_parts.append("💡 **Recommendation:** Extend weekday promotions for low-performing cuisines.\n")

            # Weather Impact
            if "weather_impact" in facts:
                markdown_parts.append("\n## 🌦 Weather Impact Analysis")
                for k,v in facts["weather_impact"].items():
                    markdown_parts.append(f"- {str(k)}: ${v:,.2f}")
                markdown_parts.append("💡 **Recommendation:** Introduce comfort-food specials during rainy days.\n")

            # Top Cuisines
            if "top_cuisines" in facts:
                markdown_parts.append("\n## 🍽 Top Performing Cuisines")
                for k,v in facts["top_cuisines"].items():
                    markdown_parts.append(f"- {k}: ${v:,.2f}")
                markdown_parts.append("💡 **Recommendation:** Focus marketing budget on top cuisines and bundle popular items.\n")

            # ------------------------------------------------------------
            # Visualizations Section
            if figures:
                markdown_parts.append("## 📈 Visualizations")
                markdown_parts.append("*Displayed in interactive Streamlit interface.*")

            # Methodology Footer
            markdown_parts.append("---\n### Methodology")
            markdown_parts.append("1. Retriever – data collection \n2. Researcher – statistical analysis \n3. Writer – structured report generation \n4. Reviewer – LLM refinement")
            markdown_parts.append("\n\n*Auto-generated by Writer Agent*")

            return DraftReport(markdown="\n".join(markdown_parts))

        except Exception as e:
            return DraftReport(markdown=f"# Error\n{e}")
